[build]
builder = "nixpacks"

[deploy]
startCommand = "npm run backend"
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 3

[variables]
NODE_ENV = "production"
PORT = "3001"

[services.web]
port = 3001
healthcheckPath = "/api/health"
healthcheckTimeout = 30
deploymentPriority = 1

